name: CI
on:
  push:
    branches: [ main, connected-to-backend]
  pull_request:
    branches: [ main, connected-to-backend]
permissions:
  contents: read
jobs:
  Lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: npm
      - run: 'npm i && npm run lint'
